### ISSUE TITLE
Error setting up entry Roomba for roomba

### ISSUE THREAD

**Issue by mike9011** [simbaja/ha_roomba#1]
Hi,

I'm testing your custom component, but it keeps giving me errors running the latest version of HA.

```
Logger: homeassistant.config_entries
Source: custom_components/roomba/__init__.py:129
Integration: iRobot Roomba and Braava
First occurred: 09:37:29 (2 occurrences)
Last logged: 09:37:29

Error setting up entry Braava Jet for roomba
Error setting up entry Roomba for roomba
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 313, in async_setup
    result = await component.async_setup_entry(hass, self)  # type: ignore
  File "/config/custom_components/roomba/__init__.py", line 129, in async_setup_entry
    initialize_mapping_config(roomba, hass.data[DOMAIN][CONFIG])
KeyError: 'roomba'
```

```
Logger: homeassistant.helpers.frame
Source: helpers/frame.py:103
First occurred: 09:38:04 (1 occurrences)
Last logged: 09:38:04

Detected integration that accessed discovery_info['ip'] instead of discovery_info.ip; this will fail in version 2022.6. Please report issue to the custom component author for roomba using this method at custom_components/roomba/config_flow.py, line 82: self._async_abort_entries_match({CONF_HOST: discovery_info[IP_ADDRESS]})
```

**Comment by simbaja** [comment]
I haven't had a chance to update for the latest version yet; however, I think that particular one can probably be solved by putting a "roomba:" section in your config.yaml.  I can probably revise other aspects (such as that warning) over the weekend.

**Comment by simbaja** [comment]
I think that that error should be resolved; however, it looks like Roomba screwed us on this and stopped sending the position in the latest firmware, see: https://github.com/koalazak/dorita980/issues/148.  So, no matter what this thing won't work at the moment.

**Comment by simbaja** [comment]
Looks like we're SOL, I'm going to close this.
